version: '3.8'

services:
  php-apache:
    container_name: ${PROYECT_NAME}-apache
    # Otras configuraciones...
    labels:
      - "com.example.environment=production"
    build:
      context: .
    ports:
      - ${APACHE_PORT}:80

    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${CONFIG_FILE}:/etc/apache2/sites-enabled/000-default.conf
      - ${APACHE_LOG_DIR}:/var/log/apache2

    depends_on:
      - mysql
    networks:
      portafolio-net:
        # ipv4_address: ${MY_IP}.10

  mysql:
    container_name: ${PROYECT_NAME}-mysql
    labels:
      - "com.example.environment=production"
    image: mysql:8.0
    ports:
     - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      portafolio-net:
        # ipv4_address: ${MY_IP}.11  

networks:
  portafolio-net:
    
volumes:
  mysql-data:
