version: '3.8'

services:
    android-emulator:
        image: budtmo/docker-android:emulator_11.0
        container_name: android_emulator
        privileged: true
        ports:
            - '6080:6080' # Web VNC
            - '5555:5555' # ADB
        environment:
            - DEVICE=Nexus 5
            - APPIUM=false
            - WEB_VNC=true
            - EMULATOR_ARGS=-no-window -gpu swiftshader_indirect
        volumes:
            - ./data:/root
        shm_size: 2gb
        networks:
            - web

networks:
    web:
        external: true
