name: Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Stop existing containers
      run: sudo docker compose down

    - name: Build and start containers
      run: sudo docker compose up --build -d
