# Dockerfile-php-fpm
FROM php:8.2-fpm

LABEL maintainer="Newal Medina"

# |--------------------------------------------------------------------------|
# | Instalación de dependencias y extensiones PHP                             |
# |--------------------------------------------------------------------------|
RUN apt-get update \
    && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libbz2-dev \
        libzip-dev \
        libxrender1 \
        libfontconfig \
        curl \
        git \
        unzip \
        nano \
        vim \
        htop \
        bash-completion \
        net-tools \
        iproute2 \
        gnupg2 \
        libtidy-dev \
        openssl \
        libssl-dev \
        libicu-dev \
        libkrb5-dev \
        libxml2-dev \
        libldap2-dev \
        sudo \
    && docker-php-ext-install \
        pdo_mysql \
        mysqli \
        zip \
        bz2 \
        bcmath \
        tidy \
        intl \
        soap \
        pcntl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-enable tidy \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-install ldap \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# |--------------------------------------------------------------------------|
# | Configuración Opcache para Livewire/Laravel                              |
# |--------------------------------------------------------------------------|
RUN docker-php-ext-install opcache \
    && echo "opcache.enable=1" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.enable_cli=1" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.memory_consumption=256" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.interned_strings_buffer=16" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.max_accelerated_files=10000" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.revalidate_freq=0" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.validate_timestamps=0" >> /usr/local/etc/php/conf.d/opcache.ini

# Configurar zona horaria
RUN ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime \
    && echo "Europe/Madrid" > /etc/timezone

# Permisos de www-data
RUN chown -R www-data:www-data /var/www
WORKDIR /var/www/html

# Instalar Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php
# Instalar supervisord
RUN apt-get update && apt-get install -y supervisor \
    && mkdir -p /var/log/supervisor
# Copiar script de arranque
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]
