services:
  php-apache:
    container_name: ${PROYECT_NAME}-apache
    build:
      context: .
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "${DOCUMENT_ROOT}:/var/www/html"
      - "${PHP_INI}:/usr/local/etc/php/php.ini"
      - "${CONFIG_FILE}:/etc/apache2/sites-enabled/000-default.conf"
      - "${APACHE_LOG_DIR}:/var/log/apache2"
    networks:
      - web  # Cambiado de 'portafolio-net' a 'web'
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 3m          # Chequea cada 3 minutos (en vez de 1)
      timeout: 5s           # Espera máximo 5 segundos por respuesta
      retries: 3            # Marca como unhealthy tras 3 fallos consecutivos
      start_period: 1m      # Da 1 minuto para que el contenedor termine de iniciar

networks:
  web:
    external: true  # Usamos la red externa 'web'
