memory_limit = 8G
post_max_size = 8G
upload_max_filesize = 8G
date.timezone = "Europe/Madrid"

; opcache.enable=1
; opcache.enable_cli=1
; opcache.memory_consumption=256
; opcache.max_accelerated_files=10000
; opcache.validate_timestamps=0
; opcache.revalidate_freq=0

; ; Opcional: PHP 8.2 JIT para mejorar performance de Livewire
; opcache.jit=1205
; opcache.jit_buffer_size=100M
